easy_admin:
    entities:
        Menu:
            class: Stipic\EasyMenuBundle\Entity\Menu
            label: 'Menu'

            form:
                fields:
                    - name
                    - description
            list:
                fields:
                    - id
                    - name
                    - description
                    - menuColumns
                    - { property: 'createdAt', type_options: { required: false }}